import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // Electron main/preload must be CommonJS (the sandboxed preload cannot load ES modules).
    files: ["desktop/**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Desktop build output and downloaded binaries:
    "dist-desktop/**",
    "desktop/bin/**",
    // Generated by scripts/copy-ffmpeg-worker.mjs:
    "public/ffmpeg/**",
  ]),
]);

export default eslintConfig;
